### ISSUE TITLE
Play button issue (Minecraft-Box)

### ISSUE THREAD

**Issue by Horsyy** [lukechu10/Minecraft-Box#5]
Even i try to use the Play button, nothing happens and i've tryied to fix it but i got no clue what is going on.

**Comment by lukechu10** [comment]
I have not implemented it yet. I am deciding whether I should try to create the launching mechanism myself or use a library. However, there does not seem to be libraries for nodeJS.

**Comment by Horsyy** [comment]
To be honest i would appreciate it if you continue this project and help me finish it.

**Comment by lukechu10** [comment]
This project will be using this library: https://github.com/Voxelum/ts-minecraft#readme or on www.npmjs.org: `ts-minecraft`
